# Generated by Django 4.2.19 on 2025-02-25 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
                ("question_created_datetime", models.DateTimeField(auto_now_add=True)),
                ("response_text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RagData",
            fields=[
                ("data_id", models.AutoField(primary_key=True, serialize=False)),
                ("data_text", models.TextField()),
                ("image_urls", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        editable=False, max_length=16, primary_key=True, serialize=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("expired_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                ("search_log_id", models.AutoField(primary_key=True, serialize=False)),
                ("searching_time", models.DateTimeField(auto_now_add=True)),
                (
                    "data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.ragdata",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.chat"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chat",
            name="data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.ragdata",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.user"
            ),
        ),
    ]
