# Generated by Django 4.2.19 on 2025-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_activity",
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
