# Generated by Django 4.2.19 on 2025-02-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
