# Generated by Django 4.2.24 on 2026-05-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('chat', '0004_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='knowledge.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Employee'), ('MANAGER', 'Middle Manager'), ('ADMIN', 'C-Level Admin')], default='USER', max_length=10),
        ),
    ]
