# Generated by Django 4.2.24 on 2026-05-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_ingestmanifest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("public", "공개"),
                    ("internal", "사내 공유"),
                    ("confidential", "대외비"),
                    ("restricted", "기밀"),
                ],
                default="internal",
                help_text="이 레벨 이하 sensitivity 의 chunk 만 retrieve 가능",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ingestmanifest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
