# Generated by Django 4.2.24 on 2026-05-29 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_user_managers_user_groups_user_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_message_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content_text", models.TextField(blank=True, default="")),
                (
                    "redacted_count",
                    models.IntegerField(
                        default=0,
                        help_text="Layer 3 ACL/keyword redactions during retrieval (assistant)",
                    ),
                ),
                (
                    "moderation_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"inbound":[],"outbound":[],"retrieval_redacted":N}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "data",
                    models.ForeignKey(
                        blank=True,
                        help_text="RAG context snapshot (assistant turn only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.ragdata",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("file", "File")], max_length=10
                    ),
                ),
                ("filename", models.CharField(max_length=240)),
                ("mime_type", models.CharField(blank=True, default="", max_length=120)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "storage_path",
                    models.CharField(
                        help_text="Relative to MEDIA_ROOT", max_length=512
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="content hash for dedup",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingest_manifest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Filled when the attachment was ingested into the vector store.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.ingestmanifest",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_3154fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["deleted_at"], name="chat_messag_deleted_73bd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-last_message_at"],
                name="chat_conver_user_id_539cc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["deleted_at"], name="chat_conver_deleted_36a72f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["message", "kind"], name="chat_attach_message_f86b4f_idx"
            ),
        ),
    ]
