# Generated by Django 4.2.24 on 2026-05-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_backfill_legacy_chats"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="persona",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1_RETAIL", "P1 매장 직원"),
                    ("P2_B2B", "P2 B2B 영업"),
                    ("P3_HQ", "P3 본사 마케팅/영업기획"),
                    ("P4_OUTBOUND", "P4 외판/콜센터"),
                ],
                help_text="페르소나 → 접근 가능 audience_tier 매트릭스. null = public + retail 만 노출.",
                max_length=20,
                null=True,
            ),
        ),
    ]
