# Generated by Django 4.2.24 on 2026-05-31 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_add_user_persona"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_persona",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("requested_query", models.TextField()),
                ("allowed_tiers", models.JSONField(default=list)),
                (
                    "detected_tiers",
                    models.JSONField(
                        default=list,
                        help_text="질문이 의도한 것으로 추정되는 tier (heuristic 또는 LLM 분류).",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("BLOCKED", "권한 밖 — 차단"),
                            ("REDIRECTED", "다른 채널로 안내"),
                            ("EMPTY_FALLBACK", "권한 내 결과 없음"),
                        ],
                        default="EMPTY_FALLBACK",
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalation_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="chat_escala_user_id_e86ff2_idx",
                    ),
                    models.Index(
                        fields=["from_persona", "occurred_at"],
                        name="chat_escala_from_pe_739f01_idx",
                    ),
                    models.Index(
                        fields=["decision"], name="chat_escala_decisio_b7db21_idx"
                    ),
                ],
            },
        ),
    ]
