# Generated by Django 4.2.24 on 2026-05-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0005_user_department_user_email_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='예: chat.send, knowledge.product.search', max_length=100)),
                ('resource', models.CharField(blank=True, help_text='대상 모델 이름', max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='chat.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx')],
            },
        ),
    ]
