# Generated by Django 4.2.19 on 2025-02-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_user_last_activity_alter_user_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaData",
            fields=[
                (
                    "key",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("string_value", models.TextField(blank=True, null=True)),
                ("integer_value", models.IntegerField(blank=True, null=True)),
                ("float_value", models.FloatField(blank=True, null=True)),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("json_value", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
