"""B1 — chat.User AbstractBaseUser migration tests.

Verifies:
- AUTH_USER_MODEL points to chat.User
- USERNAME_FIELD == "email", email is unique
- UserManager.create_user / create_superuser
- password hashing (check_password)
- is_active/is_staff defaults
- existing user_id / uuid auto-generation still works
"""
from __future__ import annotations

from django.conf import settings
from django.contrib.auth import get_user_model
from django.test import TestCase


class UserModelContractTest(TestCase):
    def test_auth_user_model_setting(self):
        self.assertEqual(settings.AUTH_USER_MODEL, "chat.User")

    def test_username_field_is_email(self):
        User = get_user_model()
        self.assertEqual(User.USERNAME_FIELD, "email")

    def test_required_fields(self):
        User = get_user_model()
        self.assertEqual(list(User.REQUIRED_FIELDS), [])

    def test_create_user_hashes_password(self):
        User = get_user_model()
        u = User.objects.create_user(email="a@triplechat.test", password="Triple!23")
        self.assertTrue(u.check_password("Triple!23"))
        self.assertFalse(u.check_password("wrong"))
        # raw password is never stored
        self.assertNotEqual(u.password, "Triple!23")
        self.assertTrue(u.password.startswith("pbkdf2_") or u.password.startswith("argon2"))

    def test_create_user_defaults(self):
        User = get_user_model()
        u = User.objects.create_user(email="b@triplechat.test", password="x")
        self.assertTrue(u.is_active)
        self.assertFalse(u.is_staff)
        self.assertFalse(u.is_superuser)
        self.assertEqual(u.role, "USER")
        self.assertEqual(u.access_level, "internal")

    def test_create_superuser(self):
        User = get_user_model()
        u = User.objects.create_superuser(email="root@triplechat.test", password="x")
        self.assertTrue(u.is_superuser)
        self.assertTrue(u.is_staff)
        self.assertTrue(u.is_active)

    def test_email_unique(self):
        from django.db import IntegrityError
        User = get_user_model()
        User.objects.create_user(email="dup@triplechat.test", password="x")
        with self.assertRaises(IntegrityError):
            User.objects.create_user(email="dup@triplechat.test", password="y")

    def test_user_id_autogenerated(self):
        User = get_user_model()
        u = User.objects.create_user(email="c@triplechat.test", password="x")
        # U + 4digits + 0001 + 4digits = 13 chars (see chat/models.py save())
        self.assertTrue(u.user_id.startswith("U"))
        self.assertEqual(len(u.user_id), 13)
        self.assertIn("0001", u.user_id)

    def test_create_user_requires_email(self):
        User = get_user_model()
        with self.assertRaises(ValueError):
            User.objects.create_user(email="", password="x")


class LoginEndpointTest(TestCase):
    """B3 contract — POST /api/v1/triple/auth/login/ + /logout/ via session auth."""

    def test_login_success_returns_user_info(self):
        from django.contrib.auth import get_user_model
        User = get_user_model()
        User.objects.create_user(
            email="login@triplechat.test", password="Triple!23",
            access_level="confidential", role="MANAGER",
        )
        resp = self.client.post(
            "/api/v1/triple/auth/login/",
            {"email": "login@triplechat.test", "password": "Triple!23"},
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 200, resp.content)
        body = resp.json()
        self.assertEqual(body["email"], "login@triplechat.test")
        self.assertEqual(body["role"], "MANAGER")
        self.assertEqual(body["access_level"], "confidential")
        self.assertIn("user_id", body)

    def test_login_wrong_password_401(self):
        from django.contrib.auth import get_user_model
        User = get_user_model()
        User.objects.create_user(email="x@triplechat.test", password="Triple!23")
        resp = self.client.post(
            "/api/v1/triple/auth/login/",
            {"email": "x@triplechat.test", "password": "wrong"},
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 401)

    def test_login_inactive_user_denied(self):
        from django.contrib.auth import get_user_model
        User = get_user_model()
        u = User.objects.create_user(email="dead@triplechat.test", password="x")
        u.is_active = False
        u.save()
        resp = self.client.post(
            "/api/v1/triple/auth/login/",
            {"email": "dead@triplechat.test", "password": "x"},
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 401)

    def test_logout_flushes_session(self):
        from django.contrib.auth import get_user_model
        User = get_user_model()
        User.objects.create_user(email="lo@triplechat.test", password="Triple!23")
        self.client.post(
            "/api/v1/triple/auth/login/",
            {"email": "lo@triplechat.test", "password": "Triple!23"},
            content_type="application/json",
        )
        resp = self.client.post("/api/v1/triple/auth/logout/")
        self.assertEqual(resp.status_code, 204)
