# Generated by Django 4.2.24 on 2026-05-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0005_user_department_user_email_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(help_text='예: 경쟁사, 고객명, 비속어, 기밀', max_length=50)),
                ('severity', models.CharField(choices=[('MASK', '마스킹 후 전송 (PII)'), ('WARNING', '경고 후 전송 (감사 기록)'), ('BLOCK', '즉시 차단')], default='WARNING', max_length=10)),
                ('direction', models.CharField(choices=[('INBOUND', '사용자 입력만 (LLM으로 가기 전)'), ('OUTBOUND', 'LLM 응답만'), ('BOTH', '양방향')], default='BOTH', max_length=10)),
                ('mask_replacement', models.CharField(default='[REDACTED]', help_text='severity=MASK일 때 어느 문자열로 치환할지', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-severity', 'category', 'word'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_words', models.JSONField(default=list)),
                ('matched_categories', models.JSONField(default=list)),
                ('action', models.CharField(choices=[('BLOCKED', '차단됨'), ('WARNED', '경고 기록'), ('MASKED', '마스킹됨')], max_length=10)),
                ('source', models.CharField(choices=[('INBOUND', '사용자 입력'), ('OUTBOUND', 'LLM 응답')], max_length=10)),
                ('original_excerpt', models.TextField(blank=True, help_text='감지 시점 원문 (최대 500자)')),
                ('sanitized_excerpt', models.TextField(blank=True, help_text='마스킹/필터 후 텍스트')),
                ('reviewed', models.BooleanField(default=False, help_text='관리자 검수 완료 여부')),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='chat.chat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='chat.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='moderation__created_5b13b7_idx'), models.Index(fields=['action', 'reviewed'], name='moderation__action_4c11ac_idx')],
            },
        ),
    ]
