# Generated by Django 4.2.24 on 2026-05-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("INBOUND", "사용자 입력"),
                    ("OUTBOUND", "LLM 응답"),
                    ("UPLOAD", "문서 업로드"),
                    ("RETRIEVAL", "벡터 검색 결과"),
                ],
                max_length=10,
            ),
        ),
    ]
