# Generated by Django 4.2.24 on 2026-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_alter_moderationlog_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="forbiddenword",
            name="pattern_type",
            field=models.CharField(
                choices=[
                    ("KW", "키워드 (대소문자 무시 부분 일치)"),
                    ("RE", "정규식 (re.search)"),
                ],
                default="KW",
                help_text="KW=리터럴 부분 일치, RE=정규식 (예: \\d{6}-\\d{7})",
                max_length=2,
            ),
        ),
    ]
