# Generated by Django 4.2.24 on 2026-05-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_user_access_level_alter_ingestmanifest_id"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="원본 파일명 (확장자 포함)", max_length=240
                    ),
                ),
                (
                    "source_uri",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="file:// 또는 upload:// 키 — IngestManifest 와 연결",
                        max_length=512,
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "공개"),
                            ("internal", "사내 공유"),
                            ("confidential", "대외비"),
                            ("restricted", "기밀 (인덱싱 차단)"),
                        ],
                        db_index=True,
                        default="internal",
                        help_text="업로드 시 부여. restricted = 벡터 스토어 진입 차단",
                        max_length=20,
                    ),
                ),
                ("sensitivity_set_at", models.DateTimeField(auto_now=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensitivity_set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docs_classified",
                        to="chat.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["sensitivity"], name="knowledge_d_sensiti_650181_idx"
                    ),
                    models.Index(
                        fields=["source_uri"], name="knowledge_d_source__cd9094_idx"
                    ),
                ],
            },
        ),
    ]
