# Generated by Django 4.2.30 on 2026-05-28 06:00

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_document"),
    ]

    operations = [
        CreateExtension("vector"),
        migrations.CreateModel(
            name="VectorChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_id",
                    models.CharField(
                        db_index=True,
                        help_text="Deterministic SHA256 id (same as ChromaSink)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Chunk text used for retrieval"),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=3072, help_text="Gemini text-embedding-004 vector"
                    ),
                ),
                (
                    "source_file",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "공개"),
                            ("internal", "사내 공유"),
                            ("confidential", "대외비"),
                            ("restricted", "기밀 (인덱싱 차단)"),
                        ],
                        db_index=True,
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("page", models.IntegerField(blank=True, null=True)),
                ("section", models.CharField(blank=True, default="", max_length=200)),
                ("doc_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("extra_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sensitivity"], name="knowledge_v_sensiti_596202_idx"
                    ),
                    models.Index(
                        fields=["source_file"], name="knowledge_v_source__398854_idx"
                    ),
                ],
            },
        ),
    ]
