# Generated by Django 4.2.24 on 2026-05-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_vectorchunk_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="collection",
            field=models.CharField(
                choices=[
                    ("training", "학습 자료"),
                    ("policy", "사규·정책"),
                    ("sales", "영업 데이터"),
                    ("user", "유저 추가"),
                ],
                db_index=True,
                default="policy",
                help_text="도메인 분류 — 검색 시 namespace 필터로 사용",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vectorchunk",
            name="collection",
            field=models.CharField(
                choices=[
                    ("training", "학습 자료"),
                    ("policy", "사규·정책"),
                    ("sales", "영업 데이터"),
                    ("user", "유저 추가"),
                ],
                db_index=True,
                default="policy",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["collection"], name="knowledge_d_collect_e53d99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vectorchunk",
            index=models.Index(
                fields=["collection"], name="knowledge_v_collect_565058_idx"
            ),
        ),
    ]
